/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Consumer } from "./Consumer";
export * as factories from "./factories";
export { Consumer__factory } from "./factories/Consumer__factory";
